### PR TITLE
Fix "iff" typo and unpaired curly bracket in Javadoc

### PR DESCRIPTION
**Pull request by Philzen**
Analogous to https://github.com/FasterXML/jackson-databind/pull/4502

Also took the liberty to remove the no-arg constructor via 513900451a3117b0d733ce848df3595805999e21.

### CODE REVIEW

**Comment by pjfanning** [comment]
-1 to mixing unrelated fixes in a PR

iff is a word - https://en.wiktionary.org/wiki/iff#:~:text=(mathematics%2C%20logic)%20Short%20for%20if%20and%20only%20if.

**Comment by Philzen** [comment]
> -1 to mixing unrelated fixes in a PR

Completely agree – i tend to hold it the same way, however different projects have different rules of engagement regarding this, and this being my first contribution to Jackson i thought i'd simply await your advise. Moved the commit over to #251.

Concerning the main scope of this PR, i'm happy to follow whatever is decided in https://github.com/FasterXML/jackson-databind/pull/4502

**Review by cowtowncoder — APPROVED** [review]
Here making "iff" simple "if" makes sense, and curly is indeed extraneous.

**Comment by cowtowncoder** [comment]
Since PR is now split & changes make sense, LGTM.
Just need 2 things: 

1. Re-base against 2.18 (no benefit from backporting)
2. CLA (as per my note on another issue)

and will merge.

**Comment by Philzen** [comment]
@cowtowncoder CLA has been signed and sent.

I've now opened #252 for the 2.18 branch. Let me briefly explain the reasoning behind me initially starting with 2.15.

1. i checked https://github.com/FasterXML/jackson/wiki/Jackson-Releases which lists 2.15 as "open branch". I guess i must have misunderstood this as "open for contributions" / "actively maintained" – though i understand 2.15 is now in maintenance mode, or even EOL, is it?
2. Spring Boot (which probably is the biggest attractor bringing people into contact with Jackson for the first time – at least it was in my case) [has 2.15.4 in their latest release](https://github.com/spring-projects/spring-boot/releases/tag/v3.2.3). Even the upcoming 3.3.0 release of spring boot won't be shipping with 2.18, [but 2.17.0](https://github.com/spring-projects/spring-boot/releases/tag/v3.3.0-M3) – but i now understand is the latest available release. That's why i my understanding would be that is minimum version to still support.

As said, i'm otherwise happy to backport any of my PRs to 2.17 and below.

**Comment by cowtowncoder** [comment]
@Philzen ok: in this context "open branch" simply means that further releases might be made. It is also possible that the list may be out of date. But I can definitely see how this is confusing so I can see the reasoning behind selecting 2.15 for maximum benefit.

I'll see if I should update that Wiki page, regardless.

**Pull request closed without merging**
